In [1]:
import tensorflow as tf
print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.18.0


In [2]:
# Create different types of tensors
scalar = tf.constant(10)  # Scalar tensor
vector = tf.constant([1, 2, 3, 4])  # Vector tensor
matrix = tf.constant([[1, 2], [3, 4]])  # Matrix tensor
tensor_3d = tf.random.uniform(shape=(2, 3, 4))  # 3-dimensional tensor with random values

# Print tensors
print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)
print("3D Tensor:\n", tensor_3d)

# Tensor attributes
print("\nAttributes of 3D tensor:")
print("Shape:", tensor_3d.shape)
print("Rank:", tensor_3d.ndim)
print("Data Type:", tensor_3d.dtype)
print("Size (total elements):", tf.size(tensor_3d).numpy())


Scalar: tf.Tensor(10, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3D Tensor:
 tf.Tensor(
[[[0.26546013 0.12575948 0.23182845 0.62575746]
  [0.78491044 0.51070046 0.47100508 0.31743848]
  [0.38127995 0.76864874 0.39638603 0.6896615 ]]

 [[0.16726863 0.7004707  0.01327777 0.910341  ]
  [0.5044761  0.90391207 0.10856915 0.7494    ]
  [0.06809115 0.4373542  0.10621142 0.8720951 ]]], shape=(2, 3, 4), dtype=float32)

Attributes of 3D tensor:
Shape: (2, 3, 4)
Rank: 3
Data Type: <dtype: 'float32'>
Size (total elements): 24


In [3]:
# Create a 2D tensor for demonstration
tensor_2d = tf.constant([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original Tensor:\n", tensor_2d.numpy())

# Indexing single element
print("\nSingle Element [0, 1]:", tensor_2d[0, 1].numpy())

# Slicing rows
print("\nFirst Row:", tensor_2d[0].numpy())
print("Last two Rows:\n", tensor_2d[1:].numpy())

# Slicing columns
print("\nSecond Column:", tensor_2d[:, 1].numpy())

# Advanced slicing (submatrix)
print("\nSubmatrix (first two rows, last two columns):\n", tensor_2d[:2, 1:].numpy())


Original Tensor:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Single Element [0, 1]: 20

First Row: [10 20 30]
Last two Rows:
 [[40 50 60]
 [70 80 90]]

Second Column: [20 50 80]

Submatrix (first two rows, last two columns):
 [[20 30]
 [50 60]]


In [4]:
# Original tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:\n", tensor.numpy())

# Reshape tensor to (3, 2)
reshaped_tensor = tf.reshape(tensor, (3, 2))
print("\nReshaped Tensor (3,2):\n", reshaped_tensor.numpy())

# Expand dimensions for broadcasting
expanded_tensor = tf.expand_dims(tensor, axis=-1)  # shape becomes (2,3,1)
print("\nExpanded Tensor shape:", expanded_tensor.shape)

# Broadcasting example
broadcast_tensor = tensor + tf.constant([10, 20, 30])  # Adds to each row
print("\nBroadcasted Addition:\n", broadcast_tensor.numpy())


Original Tensor:
 [[1 2 3]
 [4 5 6]]

Reshaped Tensor (3,2):
 [[1 2]
 [3 4]
 [5 6]]

Expanded Tensor shape: (2, 3, 1)

Broadcasted Addition:
 [[11 22 33]
 [14 25 36]]


In [5]:
# Create two tensors
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# Arithmetic operations
add_result = tensor_a + tensor_b
subtract_result = tensor_b - tensor_a
multiply_result = tensor_a * tensor_b  # Element-wise multiplication
divide_result = tensor_b / tensor_a

# Using tf.math module
square_result = tf.math.square(tensor_a)
sqrt_result = tf.math.sqrt(tf.cast(tensor_b, tf.float32))

# Display the results
print("Addition:\n", add_result.numpy())
print("\nSubtraction:\n", subtract_result.numpy())
print("\nElement-wise Multiplication:\n", multiply_result.numpy())
print("\nElement-wise Division:\n", divide_result.numpy())
print("\nSquare (tf.math.square):\n", square_result.numpy())
print("\nSquare Root (tf.math.sqrt):\n", sqrt_result.numpy())


Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[4 4]
 [4 4]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Element-wise Division:
 [[5.         3.        ]
 [2.33333333 2.        ]]

Square (tf.math.square):
 [[ 1  4]
 [ 9 16]]

Square Root (tf.math.sqrt):
 [[2.236068  2.4494898]
 [2.6457512 2.828427 ]]


In [6]:
# Define two matrices
matrix_x = tf.constant([[1, 2, 3], [4, 5, 6]])
matrix_y = tf.constant([[7, 8], [9, 10], [11, 12]])

# Matrix multiplication using tf.matmul()
matmul_result = tf.matmul(matrix_x, matrix_y)

# Matrix multiplication using '@' operator
matmul_operator_result = matrix_x @ matrix_y

# Display results
print("Matrix multiplication with tf.matmul():\n", matmul_result.numpy())
print("\nMatrix multiplication with '@' operator:\n", matmul_operator_result.numpy())


Matrix multiplication with tf.matmul():
 [[ 58  64]
 [139 154]]

Matrix multiplication with '@' operator:
 [[ 58  64]
 [139 154]]


In [7]:
# Define a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Reduction operations
sum_all = tf.reduce_sum(tensor)
sum_columns = tf.reduce_sum(tensor, axis=0)
sum_rows = tf.reduce_sum(tensor, axis=1)

mean_all = tf.reduce_mean(tf.cast(tensor, tf.float32))
max_value = tf.reduce_max(tensor)

# Display results
print("Sum of all elements:", sum_all.numpy())
print("Sum across columns:", sum_columns.numpy())
print("Sum across rows:", sum_rows.numpy())

print("\nMean of all elements:", mean_all.numpy())
print("Max value in tensor:", max_value.numpy())


Sum of all elements: 21
Sum across columns: [5 7 9]
Sum across rows: [ 6 15]

Mean of all elements: 3.5
Max value in tensor: 6


In [8]:
# Define two tensors for concatenation and stacking
tensor_x = tf.constant([[1, 2], [3, 4]])
tensor_y = tf.constant([[5, 6], [7, 8]])

# Concatenate along rows and columns
concat_rows = tf.concat([tensor_x, tensor_y], axis=0)
concat_columns = tf.concat([tensor_x, tensor_y], axis=1)

# Stack tensors (new dimension)
stacked_tensor = tf.stack([tensor_x, tensor_y])

# Splitting tensor
split_tensors = tf.split(concat_rows, num_or_size_splits=2, axis=0)

# Display results
print("Concatenated along rows:\n", concat_rows.numpy())
print("\nConcatenated along columns:\n", concat_columns.numpy())
print("\nStacked tensor (new dimension):\n", stacked_tensor.numpy())
print("\nSplit tensors:")
for idx, t in enumerate(split_tensors):
    print(f"Tensor {idx+1}:\n", t.numpy())


Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]

Stacked tensor (new dimension):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Split tensors:
Tensor 1:
 [[1 2]
 [3 4]]
Tensor 2:
 [[5 6]
 [7 8]]


In [9]:
# Example tensors
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication using einsum
matmul_einsum = tf.einsum('ij,jk->ik', a, b)

# Element-wise multiplication and sum (dot product)
dot_product = tf.einsum('ij,ij->', a, b)

# Transpose operation
transpose_a = tf.einsum('ij->ji', a)

# Batch matrix multiplication example
a_batch = tf.random.uniform((3, 2, 3))
b_batch = tf.random.uniform((3, 3, 4))
batch_matmul = tf.einsum('bij,bjk->bik', a_batch, b_batch)

# Display results
print("Matrix multiplication (einsum):\n", matmul_einsum.numpy())
print("\nDot product (einsum):", dot_product.numpy())
print("\nTranspose (einsum):\n", transpose_a.numpy())
print("\nBatch matrix multiplication shape (einsum):", batch_matmul.shape)


Matrix multiplication (einsum):
 [[19 22]
 [43 50]]

Dot product (einsum): 70

Transpose (einsum):
 [[1 3]
 [2 4]]

Batch matrix multiplication shape (einsum): (3, 2, 4)


In [10]:
# Create a tensor for advanced indexing and masking
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])

# Boolean Masking (tf.boolean_mask)
mask = [True, False, True]
masked_tensor = tf.boolean_mask(tensor, mask)

# Scatter operation (tf.scatter_nd)
indices = [[0], [2]]
updates = [100, 200]
scatter_tensor = tf.scatter_nd(indices, updates, shape=[4])

# Gather operation (tf.gather_nd)
gathered_elements = tf.gather_nd(tensor, indices=[[0, 1], [2, 0]])

# Display results
print("Original tensor:\n", tensor.numpy())
print("\nBoolean masked tensor:\n", masked_tensor.numpy())
print("\nScatter tensor (tf.scatter_nd):\n", scatter_tensor.numpy())
print("\nGathered elements (tf.gather_nd):", gathered_elements.numpy())


Original tensor:
 [[1 2]
 [3 4]
 [5 6]]

Boolean masked tensor:
 [[1 2]
 [5 6]]

Scatter tensor (tf.scatter_nd):
 [100   0 200   0]

Gathered elements (tf.gather_nd): [2 5]
