In [1]:
import torch
print("PyTorch Version:", torch.__version__)
print("GPU Available:", torch.cuda.is_available())


PyTorch Version: 2.5.1+cu124
GPU Available: True


In [2]:
# Creating basic tensors
scalar = torch.tensor(10)  # Scalar tensor
vector = torch.tensor([1, 2, 3, 4])  # Vector tensor
matrix = torch.tensor([[1, 2], [3, 4]])  # Matrix tensor
tensor_3d = torch.rand((2, 3, 4))  # 3D tensor with random values

# Print tensors
print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)
print("3D Tensor:\n", tensor_3d)

# Tensor attributes
print("\nAttributes of 3D tensor:")
print("Shape:", tensor_3d.shape)
print("Rank (ndim):", tensor_3d.ndim)
print("Data Type:", tensor_3d.dtype)
print("Device:", tensor_3d.device)
print("Size (total elements):", tensor_3d.numel())


Scalar: tensor(10)
Vector: tensor([1, 2, 3, 4])
Matrix:
 tensor([[1, 2],
        [3, 4]])
3D Tensor:
 tensor([[[0.2679, 0.0673, 0.9103, 0.2175],
         [0.4749, 0.0816, 0.4531, 0.1029],
         [0.7441, 0.0234, 0.1940, 0.8755]],

        [[0.3239, 0.4338, 0.9798, 0.3904],
         [0.6626, 0.2398, 0.2591, 0.1302],
         [0.2850, 0.0802, 0.6759, 0.4057]]])

Attributes of 3D tensor:
Shape: torch.Size([2, 3, 4])
Rank (ndim): 3
Data Type: torch.float32
Device: cpu
Size (total elements): 24


In [4]:
# Create a tensor for indexing and slicing
tensor_2d = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original Tensor:\n", tensor_2d)

# Indexing single element
print("\nSingle Element [0, 1]:", tensor_2d[0, 1].item())

# Slicing rows
print("\nFirst Row:", tensor_2d[0])
print("Last two Rows:\n", tensor_2d[1:])

# Slicing columns
print("\nSecond Column:", tensor_2d[:, 1])

# Advanced slicing (submatrix)
print("\nSubmatrix (first two rows, last two columns):\n", tensor_2d[:2, 1:])


Original Tensor:
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

Single Element [0, 1]: 20

First Row: tensor([10, 20, 30])
Last two Rows:
 tensor([[40, 50, 60],
        [70, 80, 90]])

Second Column: tensor([20, 50, 80])

Submatrix (first two rows, last two columns):
 tensor([[20, 30],
        [50, 60]])


In [5]:
# Original tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:\n", tensor)

# Reshape tensor to (3, 2)
reshaped_tensor = tensor.reshape(3, 2)
print("\nReshaped Tensor (3,2):\n", reshaped_tensor)

# Unsqueeze tensor for broadcasting (adds dimension)
expanded_tensor = tensor.unsqueeze(-1)  # shape (2,3,1)
print("\nExpanded Tensor shape:", expanded_tensor.shape)

# Broadcasting example
broadcast_tensor = tensor + torch.tensor([10, 20, 30])  # Adds to each row
print("\nBroadcasted Addition:\n", broadcast_tensor)


Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Reshaped Tensor (3,2):
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Expanded Tensor shape: torch.Size([2, 3, 1])

Broadcasted Addition:
 tensor([[11, 22, 33],
        [14, 25, 36]])


In [6]:
# Define two tensors
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Arithmetic operations
add_result = tensor_a + tensor_b
subtract_result = tensor_b - tensor_a
multiply_result = tensor_a * tensor_b  # Element-wise multiplication
divide_result = tensor_b / tensor_a

# Matrix multiplication
matmul_result = torch.matmul(tensor_a, tensor_b)
matmul_operator_result = tensor_a @ tensor_b

# Display the results
print("Addition:\n", add_result)
print("\nSubtraction:\n", subtract_result)
print("\nElement-wise Multiplication:\n", multiply_result)
print("\nElement-wise Division:\n", divide_result)
print("\nMatrix multiplication with torch.matmul():\n", matmul_result)
print("\nMatrix multiplication with '@' operator:\n", matmul_operator_result)


Addition:
 tensor([[ 6,  8],
        [10, 12]])

Subtraction:
 tensor([[4, 4],
        [4, 4]])

Element-wise Multiplication:
 tensor([[ 5, 12],
        [21, 32]])

Element-wise Division:
 tensor([[5.0000, 3.0000],
        [2.3333, 2.0000]])

Matrix multiplication with torch.matmul():
 tensor([[19, 22],
        [43, 50]])

Matrix multiplication with '@' operator:
 tensor([[19, 22],
        [43, 50]])


In [7]:
# Define a tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reduction operations
sum_all = torch.sum(tensor)
sum_columns = torch.sum(tensor, axis=0)
sum_rows = torch.sum(tensor, axis=1)

mean_all = torch.mean(tensor.float())
max_value = torch.max(tensor)
min_value = torch.min(tensor)

# Display results
print("Sum of all elements:", sum_all.item())
print("Sum across columns:", sum_columns)
print("Sum across rows:", sum_rows)

print("\nMean of all elements:", mean_all.item())
print("Max value in tensor:", max_value.item())
print("Min value in tensor:", min_value.item())


Sum of all elements: 21
Sum across columns: tensor([5, 7, 9])
Sum across rows: tensor([ 6, 15])

Mean of all elements: 3.5
Max value in tensor: 6
Min value in tensor: 1


In [8]:
# Define tensors
tensor_x = torch.tensor([[1, 2], [3, 4]])
tensor_y = torch.tensor([[5, 6], [7, 8]])

# Concatenate along rows and columns
concat_rows = torch.cat([tensor_x, tensor_y], dim=0)
concat_columns = torch.cat([tensor_x, tensor_y], dim=1)

# Stack tensors (new dimension)
stacked_tensor = torch.stack([tensor_x, tensor_y])

# Splitting tensor
split_tensors = torch.split(concat_rows, split_size_or_sections=2, dim=0)

# Display results
print("Concatenated along rows:\n", concat_rows)
print("\nConcatenated along columns:\n", concat_columns)
print("\nStacked tensor (new dimension):\n", stacked_tensor)
print("\nSplit tensors:")
for idx, t in enumerate(split_tensors):
    print(f"Tensor {idx+1}:\n", t)


Concatenated along rows:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Concatenated along columns:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

Stacked tensor (new dimension):
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

Split tensors:
Tensor 1:
 tensor([[1, 2],
        [3, 4]])
Tensor 2:
 tensor([[5, 6],
        [7, 8]])


In [9]:
# Define tensors
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication using einsum
matmul_einsum = torch.einsum('ij,jk->ik', a, b)

# Dot product using einsum
dot_product = torch.einsum('ij,ij->', a, b)

# Transpose operation
transpose_a = torch.einsum('ij->ji', a)

# Batch matrix multiplication example
a_batch = torch.rand((3, 2, 3))
b_batch = torch.rand((3, 3, 4))
batch_matmul = torch.einsum('bij,bjk->bik', a_batch, b_batch)

# Display results
print("Matrix multiplication (einsum):\n", matmul_einsum)
print("\nDot product (einsum):", dot_product.item())
print("\nTranspose (einsum):\n", transpose_a)
print("\nBatch matrix multiplication shape (einsum):", batch_matmul.shape)


Matrix multiplication (einsum):
 tensor([[19, 22],
        [43, 50]])

Dot product (einsum): 70

Transpose (einsum):
 tensor([[1, 3],
        [2, 4]])

Batch matrix multiplication shape (einsum): torch.Size([3, 2, 4])


In [10]:
!pip install einops

In [11]:
from einops import rearrange, reduce, repeat
import torch

# Original tensor
tensor = torch.randn(2, 3, 4)
print("Original Tensor shape:", tensor.shape)

# Rearrange (transpose-like operation)
rearranged_tensor = rearrange(tensor, 'b h w -> b w h')
print("\nRearranged Tensor shape:", rearranged_tensor.shape)

# Reduce (sum across one dimension)
reduced_tensor = reduce(tensor, 'b h w -> b h', 'sum')
print("\nReduced Tensor shape (sum across last dim):", reduced_tensor.shape)

# Repeat tensor
repeated_tensor = repeat(tensor, 'b h w -> b h w repeat', repeat=2)
print("\nRepeated Tensor shape:", repeated_tensor.shape)


Original Tensor shape: torch.Size([2, 3, 4])

Rearranged Tensor shape: torch.Size([2, 4, 3])

Reduced Tensor shape (sum across last dim): torch.Size([2, 3])

Repeated Tensor shape: torch.Size([2, 3, 4, 2])
